version: '3.8'

services:
  app:
    build:
      context: .  # Build context is the current directory
      dockerfile: Dockerfile  # Specify the Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./my-laravel/:/var/www/html
    networks:
      - laravel
    depends_on:
      - composer
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0

  composer:
    image: composer:2
    container_name: laravel_composer
    working_dir: /var/www/html
    volumes:
      - ./my-laravel/:/var/www/html
    entrypoint: ['composer']

  webserver:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - ./my-laravel/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - dbdata_new:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - laravel

volumes:
  dbdata:
  dbdata_new:

networks:
  laravel:
    driver: bridge
